
read -dont_elaborate ../leon/amba.vhd
read -dont_elaborate ../leon/target.vhd
read -dont_elaborate ../leon/device.vhd
read -dont_elaborate ../leon/config.vhd
read -dont_elaborate ../leon/sparcv8.vhd
read -dont_elaborate ../leon/iface.vhd
read -dont_elaborate ../leon/macro.vhd
read -dont_elaborate ../leon/bprom.vhd
read -dont_elaborate ../leon/tech_generic.vhd
read -dont_elaborate ../leon/tech_virtex.vhd
read -dont_elaborate ../leon/tech_leonardo.vhd
read -dont_elaborate ../leon/tech_synplify.vhd
read -dont_elaborate ../leon/tech_atc35.vhd
read -dont_elaborate ../leon/ramlib.vhd
read -dont_elaborate ../leon/cachemem.vhd
read -dont_elaborate ../leon/icache.vhd
read -dont_elaborate ../leon/dcache.vhd
read -dont_elaborate ../leon/acache.vhd
read -dont_elaborate ../leon/cache.vhd
read -dont_elaborate ../leon/apbmst.vhd
read -dont_elaborate ../leon/ahbstat.vhd
read -dont_elaborate ../leon/ahbtest.vhd
read -dont_elaborate ../leon/ambacomp.vhd
read -dont_elaborate ../leon/ahbarb.vhd
read -dont_elaborate ../leon/lconf.vhd
read -dont_elaborate ../leon/fpulib.vhd
read -dont_elaborate ../leon/fp1eu.vhd
read -dont_elaborate ../leon/ioport.vhd
read -dont_elaborate ../leon/irqctrl.vhd
read -dont_elaborate ../leon/clkgen.vhd
read -dont_elaborate ../leon/mctrl.vhd
read -dont_elaborate ../leon/padlib.vhd
read -dont_elaborate ../leon/regfile.vhd
read -dont_elaborate ../leon/rstgen.vhd
read -dont_elaborate ../leon/timers.vhd
read -dont_elaborate ../leon/uart.vhd
read -dont_elaborate ../leon/iu.vhd
read -dont_elaborate ../leon/proc.vhd
read -dont_elaborate ../leon/wprot.vhd
read -dont_elaborate ../leon/mcore.vhd
read -dont_elaborate ../leon/leon.vhd
elaborate leon -architecture rtl
